name: Update Cuaca RUNGAU (JSON)

on:
  schedule:
    - cron: '0 */3 * * *'  # tiap 3 jam
  workflow_dispatch:

jobs:
  update-cuaca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo cuaca-bmkg
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Jalankan skrip Python untuk update cuaca_rungau.txt
        run: python update_cuaca_rungau.py

      - name: Cek isi folder setelah python run
        run: ls -l

      - name: Clone repo GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${GH_TOKEN}@github.com/pradipta570/pradipta570.github.io.git pages

      - name: Copy dan commit update cuaca_rungau.json jika ada perubahan
  run: |
    cp cuaca_rungau.json pages/
    cd pages
    git add cuaca_rungau.json
    if ! git diff --cached --quiet; then
      git commit -m "Update cuaca_rungau.json otomatis"
      git push
    else
      echo "Tidak ada perubahan, tidak perlu commit."
    fi
